### PR TITLE
feat: Add per collection override of the Tautulli watched percent

### PR DESCRIPTION
**Pull request by benscobie**
I've included a separate commit for conditionally showing the inputs, I'll revert if you'd prefer not to hide them. I struggled with the field description so let me know if you have any better ideas 😆

### CODE REVIEW

**Comment by jorenn92** [comment]
@benscobie, I'm afraid that the changes to the AddModal have affected the ability to edit rules. Importing rules from YAML or the community is also no longer functioning. The modal is quite sensitive, so I generally try to avoid making modifications to it whenever possible.

**Comment by benscobie** [comment]
> @benscobie, I'm afraid that the changes to the AddModal have affected the ability to edit rules. Importing rules from YAML or the community is also no longer functioning. The modal is quite sensitive, so I generally try to avoid making modifications to it whenever possible.

Ah damn, I'll take a look later on if I get some time. Which part of editing rules doesn't work, not saving/loading spinner forever?

**Comment by jorenn92** [comment]
> > @benscobie, I'm afraid that the changes to the AddModal have affected the ability to edit rules. Importing rules from YAML or the community is also no longer functioning. The modal is quite sensitive, so I generally try to avoid making modifications to it whenever possible.
> 
> Ah damn, I'll take a look later on if I get some time. Which part of editing rules doesn't work, not saving/loading spinner forever?

Great, no rush at all! I'm currently in a busy period, so there may be a few days between my replies.

Here are the findings from my quick tests:

- When opening the modal via the 'edit' button for an existing rule, the rules themselves are no longer loaded. Instead, an empty ruleset appears.
- Importing community rules partially works, but the initial 'empty' rule remains, which causes unexpected behavior.
- Importing YAML doesn't seem to have any effect.

**Comment by benscobie** [comment]
> > > @benscobie, I'm afraid that the changes to the AddModal have affected the ability to edit rules. Importing rules from YAML or the community is also no longer functioning. The modal is quite sensitive, so I generally try to avoid making modifications to it whenever possible.
> > 
> > 
> > Ah damn, I'll take a look later on if I get some time. Which part of editing rules doesn't work, not saving/loading spinner forever?
> 
> Great, no rush at all! I'm currently in a busy period, so there may be a few days between my replies.
> 
> Here are the findings from my quick tests:
> 
>     * When opening the modal via the 'edit' button for an existing rule, the rules themselves are no longer loaded. Instead, an empty ruleset appears.
> 
>     * Importing community rules partially works, but the initial 'empty' rule remains, which causes unexpected behavior.
> 
>     * Importing YAML doesn't seem to have any effect.

That new commit should do it, those scenarios work for me now at least. There was a lot of strange things happening with the useEffects in RuleCreator. I've removed them in favour of setting the initial state directly and updating state at the call sites. This falls under this: https://react.dev/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state

**Comment by gold007eye** [comment]
Keeping an eye on this so I can test once it makes it to docker hub pull. :)

**Comment by jorenn92** [comment]
Good news! It seems to be working now. Thanks for the updates and additions. I'll go ahead and merge the changes. Appreciate your work on this PR!

**Review by jorenn92 — APPROVED** [review]

**Pull request merged**
