### PR TITLE
fix(rules): Added Sonarr rules: 'Has unaired episodes', 'Number of mo…

### PR DESCRIPTION
**Pull request by jorenn92**
…nitored seasons / episodes' & 'Season has unaired episodes'

### CODE REVIEW

**Comment by appiekap653** [comment]
This does not work as intended 🙁

```
season.statistics.nextAiring !== undefined
``` 

I have a couple of series that I have in Maintainerr as type Season.

Those series still have unaired episodes for the current season but are being added to the collection for removal by Maintainerr.

Rule in Maintainerr:

Sonarr - Has Unaired Episodes - EQUALS - FALSE

Response from my Sonarr API:

```
  "seasons": [
      {
        "seasonNumber": 1,
        "monitored": true,
        "statistics": {
          "episodeFileCount": 0,
          "episodeCount": 0,
          "totalEpisodeCount": 18,
          "sizeOnDisk": 0,
          "releaseGroups": [],
          "percentOfEpisodes": 0.0
        }
      },
      {
        "seasonNumber": 2,
        "monitored": true,
        "statistics": {
          "nextAiring": "2023-11-16T01:00:00Z",
          "previousAiring": "2023-11-02T00:00:00Z",
          "episodeFileCount": 5,
          "episodeCount": 5,
          "totalEpisodeCount": 13,
          "sizeOnDisk": 14454217913,
          "releaseGroups": [
            "FLUX",
            "NTb"
          ],
          "percentOfEpisodes": 100.0
        }
      }
    ],
```

As Sonarr shows I have 5 episodes of the total of 13 episodes for the second season.
The next air date is also specified at: "2023-11-16T01:00:00Z" for episode 6.

Still the series is flagged for removal.
This happens with all my series that has still unaired episodes. So this isn't something like it works with some and works not for some.

I also have some series that have unaired episodes but no air date is specified yet for those episodes.

How are those series handled?

**Comment by jorenn92** [comment]
Hey, it looks like the error is located in this part:

```
if (dataType === EPlexDataType.SEASONS) {
  data.push(...season);
}
```
The spread operator can't be used, because the season object isn't iterable when the dataType is 'season', so this errors out and returns false for everything..

I thought I tested this, but apparently not good enough, thanks for letting me know! I've checked in a fix in [#575](https://github.com/jorenn92/Maintainerr/pull/575)

As for your last question, seasons with unaired episodes, but without a next air date, will return false. I don't think this is something I can avoid, since I don't see another way to find out if a series is still airing. I can't use the episodeFileCount params, since it's possible people didn't download each episode of a season. I'm all open for suggestions though :)

**Comment by appiekap653** [comment]
Maybe we can use the data points I suggested in the first place.
Those data points also fixes the possibility of not downloaded each episode.

#509 

Sonarr - Total amount of episodes for this season
Plex - Amount of available episodes for this season
Sonarr - Episode-Number of last episode of this season
Plex - Episode-Number of last seen episode

**Comment by jorenn92** [comment]
Can't you use these already existing options for this purpose? 
- Sonarr- Number of seasons / episodes (also unavailable)
- Plex - Amount of available episodes

The thing is, I can't keep up with feature requests. For now, I'm using my limited time to prioritize bug reports.

I'd like to look into the rules you requested, they are certainly possible. But they'll have to wait until I have the time for them (as do all feature requests for now).

If you really want them fast, you're free to add them and submit a PR.

**Pull request merged**
