### PR TITLE
added a notice about saving changes first before testing

### PR DESCRIPTION
**Pull request by ydkmlt84**
I personally thought the words Test SAVED were clarification enough, but there are a lot of people having this issue. Figured I could add a little helper notice. Also, my linter settings (or something) must be different than yours because it is always automatically adding those indentation changes to my commits.

I am going to attempt to put it back to the way you had it.

### CODE REVIEW

**Comment by ydkmlt84** [comment]
#1221

**Comment by jorenn92** [comment]
Hey, thanks for the PR! I'm first going to release a smaller 2.1.1 release that addresses https://github.com/jorenn92/Maintainerr/issues/1250 & https://github.com/jorenn92/Maintainerr/issues/1242, since this broke after 2.1.0. (Probably later today). After that i'll merge this one.

**Comment by jorenn92** [comment]
I'm not completely satisfied with how the design looks on mobile. In the past, I kept the button text short to prevent the buttons from appearing too large on smaller screens, but now they look oversized:

image


Would renaming "Add Rule to Section" to "Add to Section" and "Add a New Section" to "Add New Section" be a good compromise? I also feel that the "Community Rules" button is too large. While just using "Community," as I did before, feels too vague, perhaps there's a better alternative, though I'm not sure what that would be.

As for the "Test Saved" notification, it’s not working well on mobile either:

Before: 
image


Now:
 image


A potential solution could be placing the notification between the "Docs" and "Test" buttons, utilizing the full width, and restoring the "Test" buttons to their original size.

Also, if I may nitpick, I'd prefer the notification's text to be centered to the buttons in the desktop view as well. It's a tiny bit too high now:
image

**Comment by ydkmlt84** [comment]
I agree with all of those things. As I have done before when making the Maintainerr.info website, I am not good with mobile. My main goal was clarification in everything, coming from common issues I've seen in discord. 
 
 I will take a look at this today and see if I can come up with some better ideas/options. I will fix the alignment of the test saved notification on desktop view, and see if putting it above the buttons fixes it for mobile view.

**Comment by jorenn92** [comment]
> I agree with all of those things. As I have done before when making the Maintainerr.info website, I am not good with mobile. My main goal was clarification in everything, coming from common issues I've seen in discord.
> 
> I will take a look at this today and see if I can come up with some better ideas/options. I will fix the alignment of the test saved notification on desktop view, and see if putting it above the buttons fixes it for mobile view.

Thanks! If you run into any issues, just hit me up on discord. I'd be happy to help.

**Comment by ydkmlt84** [comment]
How do you feel about these changes? I swapped the test and save buttons so that left-to-right is Save first and then Test. I completely removed the text about saving first. I could get it to look fine in mobile and then it would be messed up in desktop. I think this should help clarify saving first since it's the first button when reading left to right.

Screenshot 2024-09-13 233203
Screenshot 2024-09-13 233134

For the rules buttons I made some changes too, and the Community button now says Shared. Two words of anything would make the button too big in mobile. Maybe Shared is a little less vague than Community? 

Screenshot 2024-09-13 233100
Screenshot 2024-09-13 233043

**Comment by jorenn92** [comment]
> How do you feel about these changes? I swapped the test and save buttons so that left-to-right is Save first and then Test. I completely removed the text about saving first. I could get it to look fine in mobile and then it would be messed up in desktop. I think this should help clarify saving first since it's the first button when reading left to right.
> 
> Screenshot 2024-09-13 233203 Screenshot 2024-09-13 233134
> 
> For the rules buttons I made some changes too, and the Community button now says Shared. Two words of anything would make the button too big in mobile. Maybe Shared is a little less vague than Community?
> 
> Screenshot 2024-09-13 233100 Screenshot 2024-09-13 233850 Screenshot 2024-09-13 233043

This looks a lot better! I'm not really sold on the 'shared' button name though. Perhaps something like 'Hub'? Although that might be too vague as well.

**Comment by ydkmlt84** [comment]
Closing this for now, in light of the new monorepo structure, as it is quite old. Maybe will revisit later on.

**Pull request closed without merging**
